collections:
  pages:
    output: true
    permalink: /:name

# top level stuff you probably don't need to touch
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
rdiscount:
  extensions: [smart]
permalink: /:year/:month/:day/:title:output_ext
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-archives
port: 3000
safe: true


# edit here to achieve your personal greatness
avatar: avatar-dark.png
url: http://www.manuel-huber.de
baseurl: /
cvurl: /static/pdf/Manuel-Huber-CV.pdf
title: Manuel Huber
author: Manuel "Grim" Huber
description: In love with code
email: mail@Manuel-Huber.de
github: manuelhuber
#twitter: username
linkedin: ManuelH
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Grim"

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive-layout
